/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainbooking;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author Bakr Khaled
 */
public class Book_Cancel extends javax.swing.JFrame {

    ArrayList<String> Trains = new ArrayList<>();   
    ArrayList<Integer> Trips = new ArrayList<>(); 

    int available_seats =0;
    int N;
    int Cid;

    
    
    
    public Book_Cancel() {
        initComponents();
        hide.setVisible(false);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        startPoint = new javax.swing.JTextField();
        endPoint = new javax.swing.JTextField();
        numOfBags = new javax.swing.JTextField();
        numOfSeats = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        departDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hide = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book One Of Our Trains By Filling The Following Fields");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 494, 52));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("From :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("To :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Depart Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Number Of Seats :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        getContentPane().add(startPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, -1));

        endPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPointActionPerformed(evt);
            }
        });
        getContentPane().add(endPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 170, -1));

        numOfBags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfBagsActionPerformed(evt);
            }
        });
        getContentPane().add(numOfBags, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 175, 25));
        getContentPane().add(numOfSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("Show Available Trains");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 241, 42));
        getContentPane().add(departDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Number Of Bags :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Station", "From", "To", "Date", "Available seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout hideLayout = new javax.swing.GroupLayout(hide);
        hide.setLayout(hideLayout);
        hideLayout.setHorizontalGroup(
            hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hideLayout.setVerticalGroup(
            hideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hideLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 720, 230));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 83, 35));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainbooking/index.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endPointActionPerformed

    private void numOfBagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfBagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfBagsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            if(startPoint.getText().isEmpty() || endPoint.getText().isEmpty() || departDate.getText().isEmpty() || numOfSeats.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please Enter All Fields!");
            }
            else{
                    hide.setVisible(true);

            }
            
            
            String S = startPoint.getText();
            String E = endPoint.getText();
            String D = departDate.getText();
            N = Integer.parseInt(numOfSeats.getText());
            
            DbConnection databaseConnection = new DbConnection();
            Connection c = databaseConnection.getConnection();
           
            Statement st = c.createStatement();
            String query = "Select * from trip t join train tr on t.train_name = tr.train_name";       
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                
                int id   = rs.getInt("TRIP_ID");
                String tname = rs.getString("train_name");
                String station = rs.getString("station_name");
                String trip_date = rs.getString("trip_date");
                String start_point = rs.getString("start_point");
                String end_point = rs.getString("end_point");
                available_seats   = rs.getInt("AVAILABLE_SEATS");
                
                DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
                String seats   = String.valueOf(available_seats);
                String tbData[] = { station,start_point, end_point,trip_date, seats};
                
                if(S.equals(start_point)  && E.equals(end_point) && available_seats >= N && D.equals(trip_date)){
                    Trains.add(tname);
                    Trips.add(id);
                    tblModel.addRow(tbData);                
                }
            
            }
            c.close();
        }catch(HeadlessException | NumberFormatException | SQLException e){
                System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
        int row = jTable2.getSelectedRow() ;
        
        String d = jTable2.getValueAt(row,3).toString();
        int seat = Integer.parseInt(jTable2.getValueAt(row,4).toString());

        String tn = Trains.get(row);
        int id = Trips.get(row);
        
        DbConnection databaseConnection = new DbConnection();
        Connection connection = databaseConnection.getConnection();
        
        if (connection != null) {
            try {
                Statement statement = connection.createStatement();
                String query = "SELECT * FROM login_user";
                ResultSet rs = statement.executeQuery(query);
                
                while (rs.next()) {
                    Cid = rs.getInt("ID");
                }
                String insertQuery = "INSERT INTO RESERVATION(TRIP_ID,CUSTOMER_ID,RES_DATE,RES_SEAT,Tname) VALUES (?,?,?,?,?)";
                try (PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {
                    preparedStatement.setInt(1, id);
                    preparedStatement.setInt(2, Cid);
                    preparedStatement.setString(3, d);
                    preparedStatement.setInt(4, N);
                    preparedStatement.setString(5, tn);


                    int rowsAffected = preparedStatement.executeUpdate();
                }
                
                String updateQuery1 = "UPDATE TRAIN SET AVAILABLE_SEATS = '" + (seat-N) + "' WHERE TRAIN_NAME = '" + tn + "'";

                int rowsAffected2 = statement.executeUpdate(updateQuery1);
                
                JOptionPane.showMessageDialog(null,"Reservation Successful :)");

                statement.close();
                connection.close();
                       
                this.setVisible(false);
                new CustomerIndex().setVisible(true);


            }catch(SQLException e){
                e.printStackTrace();
            }
                
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
        this.setVisible(false);
        new CustomerIndex().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField departDate;
    private javax.swing.JTextField endPoint;
    private javax.swing.JPanel hide;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField numOfBags;
    private javax.swing.JTextField numOfSeats;
    private javax.swing.JTextField startPoint;
    // End of variables declaration//GEN-END:variables
}
