/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainbooking;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author O
 */


public class UpdateUserData extends javax.swing.JFrame {
    String Type;
    int id;
    /**
     * Creates new form UpdateUserData
     */
    public UpdateUserData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("First Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 196, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 263, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Last Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 236, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 284, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Password :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 333, -1, -1));
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 193, 222, -1));
        getContentPane().add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 233, 222, -1));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 281, 222, -1));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 222, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 90, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Update My Data");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 322, 100));
        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 222, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText(" Phone :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Show Data");
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 380, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trainbooking/UpdateData.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        if("Admin".equals(Type)){
                   
            this.setVisible(false);
            new Index().setVisible(true);
        }
        else{
                 
            this.setVisible(false);
           new CustomerIndex().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           
        String firstname = Fname.getText(); 
        String lastname = Lname.getText();          
        String userEmail = Email.getText();       
        String UserPassword = Password.getText();       
        String UserPhone = Phone.getText();
        
        DbConnection databaseConnection = new DbConnection();
        Connection connection = databaseConnection.getConnection();
       
        if (connection != null) {

            if("Admin".equals(Type)){
            
                try {
                    String updateQuery1 = "UPDATE ADMIN SET FIRST_NAME = '" + firstname + "' WHERE ADMIN_ID = '" + id + "'";
                    String updateQuery2 = "UPDATE ADMIN SET LAST_NAME = '" + lastname + "' WHERE ADMIN_ID = '" + id + "'";
                    String updateQuery3 = "UPDATE ADMIN SET  EMAIL = '" + userEmail + "' WHERE ADMIN_ID = '" + id + "'";
                    String updateQuery4 = "UPDATE ADMIN SET PASSWORD = '" + UserPassword + "' WHERE ADMIN_ID = '" + id + "'";
                    String updateQuery5 = "UPDATE ADMIN SET phone = '" + UserPhone + "' WHERE ADMIN_ID = '" + id + "'";
                    
                    Statement statement = connection.createStatement();
                    int rowsAffected  = statement.executeUpdate(updateQuery1);
                    int rowsAffected2 = statement.executeUpdate(updateQuery2);
                    int rowsAffected3 = statement.executeUpdate(updateQuery3);
                    int rowsAffected4 = statement.executeUpdate(updateQuery4);
                    int rowsAffected5 = statement.executeUpdate(updateQuery5);
                    
                    
                    String update1 = "UPDATE login_user SET FIRST_NAME = '" + firstname + "' WHERE ID = '" + id + "'";
                    String update2 = "UPDATE login_user SET LAST_NAME = '" + lastname + "' WHERE ID = '" + id + "'";
                    String update3 = "UPDATE login_user SET  EMAIL = '" + userEmail + "' WHERE ID = '" + id + "'";
                    String update4 = "UPDATE login_user SET PASSWORD = '" + UserPassword + "' WHERE ID = '" + id + "'";
                    String update5 = "UPDATE login_user SET phone = '" + UserPhone + "' WHERE ID = '" + id + "'";
                    
                    int col1 = statement.executeUpdate(update1);
                    int col2 = statement.executeUpdate(update2);
                    int col3 = statement.executeUpdate(update3);
                    int col4 = statement.executeUpdate(update4);
                    int col5 = statement.executeUpdate(update5);
   
                    JOptionPane.showMessageDialog(null,"Data Updated Succssfully :)");

                    statement.close();
                    connection.close();

                }catch (SQLException e) {
                    e.printStackTrace();
                }
            
            }
            
            else{
                try {
                    String updateQuery1 = "UPDATE CUSTOMER SET FIRST_NAME = '" + firstname + "' WHERE CUSTOMER_ID = '" + id + "'";
                    String updateQuery2 = "UPDATE CUSTOMER SET LAST_NAME = '" + lastname + "' WHERE CUSTOMER_ID = '" + id + "'";
                    String updateQuery3 = "UPDATE CUSTOMER SET  CUSTOMER_EMAIL = '" + userEmail + "' WHERE CUSTOMER_ID = '" + id + "'";
                    String updateQuery4 = "UPDATE CUSTOMER SET CUSTOMER_PASSWORD = '" + UserPassword + "' WHERE CUSTOMER_ID = '" + id + "'";
                    String updateQuery5 = "UPDATE CUSTOMER SET phone = '" + UserPhone + "' WHERE CUSTOMER_ID = '" + id + "'";

                    Statement statement = connection.createStatement();
                    int rowsAffected1 = statement.executeUpdate(updateQuery1);
                    int rowsAffected2 = statement.executeUpdate(updateQuery2);
                    int rowsAffected3 = statement.executeUpdate(updateQuery3);
                    int rowsAffected4 = statement.executeUpdate(updateQuery4);
                    int rowsAffected5 = statement.executeUpdate(updateQuery5);
                    
                    String update1 = "UPDATE login_user SET FIRST_NAME = '" + firstname + "' WHERE ID = '" + id + "'";
                    String update2 = "UPDATE login_user SET LAST_NAME = '" + lastname + "' WHERE ID = '" + id + "'";
                    String update3 = "UPDATE login_user SET  EMAIL = '" + userEmail + "' WHERE ID = '" + id + "'";
                    String update4 = "UPDATE login_user SET PASSWORD = '" + UserPassword + "' WHERE ID = '" + id + "'";
                    String update5 = "UPDATE login_user SET phone = '" + UserPhone + "' WHERE ID = '" + id + "'";
                    
                    int col1 = statement.executeUpdate(update1);
                    int col2 = statement.executeUpdate(update2);
                    int col3 = statement.executeUpdate(update3);
                    int col4 = statement.executeUpdate(update4);
                    int col5 = statement.executeUpdate(update5);
                    
                    JOptionPane.showMessageDialog(null,"Data Updated Succssfully :)");

                    
                    
                    statement.close();

                }catch (SQLException e) {
                    e.printStackTrace();
                }

            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        DbConnection databaseConnection = new DbConnection();
        Connection connection = databaseConnection.getConnection();

        if (connection != null) {
            try {
                Statement statement = connection.createStatement();
                String query = "SELECT * FROM login_user";
                ResultSet rs = statement.executeQuery(query);
                while (rs.next()) {
                    String fname = rs.getString("FIRST_NAME");
                    String lname = rs.getString("LAST_NAME");
                    String phone = rs.getString("phone");
                    String email = rs.getString("EMAIL");
                    String password = rs.getString("PASSWORD");
                    Type =rs.getString("usertype");
                    id = rs.getInt("ID");

                    Fname.setText(fname);
                    Lname.setText(lname);
                    Email.setText(email);
                    Phone.setText(phone);
                    Password.setText(password);
                    break;
                }
                databaseConnection.closeConnection();


            }catch (SQLException e) {
                e.printStackTrace();
            }
        }
     
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUserData().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
